### ISSUE TITLE
TypeError: callback is not a function

### ISSUE THREAD

**Issue by loretoparisi** [baalexander/node-portscanner#41]
I get this error running:

``` javascript
portscanner.findAPortNotInUse([4443, 4444, 4447], localhostName, function(error, port) {
    if (!error) {
        console.log('Available port: ' + port);
    } else {
        console.log('There was an error');
    }
});
```

the full stack trace was

``` shell
TypeError: callback is not a function
    at /node_modules/portscanner/lib/portscanner.js:141:7
    at /node_modules/portscanner/node_modules/async/lib/async.js:578:28
    at /node_modules/portscanner/lib/portscanner.js:128:9
    at Socket.<anonymous> (/node_modules/portscanner/lib/portscanner.js:104:5)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)
```

**Comment by suksant** [comment]
@loretoparisi having the same issue with newer node versions. It works fine with node@v4.4.6 though (should also work without a problem on other minor releases).

**Comment by laggingreflex** [comment]
Fixed now. Released a new minor version 1.1.0, please check it out and let me know.
